### PR TITLE
V2 group read file not found error

### PR DESCRIPTION
**Pull request by will-moore**
This aims to fix an issue I reported at https://github.com/zarr-developers/zarr-python/issues/2412#issuecomment-2462633090
which is causing a lot of test failures when updating ome-zarr-py to use zarr v3 at https://github.com/ome/ome-zarr-py/pull/404

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by will-moore** [comment]
There are a lot of test failures above, but it looks like my test passed!

```
tests/test_v2.py .................                                       [100%]
```

**Comment by joshmoore** [comment]
This PR fixes about 100 failures in https://github.com/ome/ome-zarr-py/pull/404/files#diff-d51ad4cb28d657d5e09c58f40674b95273611983353ab5d7bb2049bbc6303f7b ; I've fixed the merge conflict and approved the workflows. 🤞🏽 that it goes green.

**Comment by joshmoore** [comment]
Looks like fixing the merge conflict led to:

```
FAILED tests/test_v2.py::test_simple_group - TypeError: LocalStore.__init__() got an unexpected keyword argument 'mode'
```

**Comment by will-moore** [comment]
Thanks @joshmoore. Updating my test, looks like it passes without the fix in this PR, so it seems to have been fixed elsewhere. Closing for now...
