### PR TITLE
Update dtype usage in zarr/meta.py

### PR DESCRIPTION
**Pull request by joshmoore**
Changes in zarr's annotations, numpy, and/or mypy have led to failures on `mypy zarr/`across a large number of PRs. This tries to take the most direct route to passing GitHub actions so that PRs can be unblocked.

Thanks to @rgommers and @seberg for jumping in.

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Failures can be seen in https://github.com/zarr-developers/zarr-python/pull/699/checks?check_run_id=1904975788

```
arr/meta.py:82: error: Incompatible return value type (got "List[Union[Tuple[str, str], Tuple[str, str, Tuple[int, ...]]]]", expected "str")
zarr/meta.py:183: error: "generic" has no attribute "real"
zarr/meta.py:184: error: "generic" has no attribute "imag"
Found 3 errors in 1 file (checked 30 source files)
```

**Comment by rgommers** [comment]
Hmm, the `dtype.descr` change surprises me. Good chance it's on purpose, but I don't really want to comb through multiple NEPs - so let's just ask @seberg.

**Comment by seberg** [comment]
Do you know what changed?  This has nothing to do with the dtype NEPs, but `np.dtype(...).descr` has _never_ returned a string as far as I can tell. The only actual change I can think of (and find!) is that we might be returning unicode strings instead of bytes somewhere around here.

**Comment by joshmoore** [comment]
Thanks, both. I was assuming it was a numpy bump that led to this, but I'll need to try to find what the change was, unless @Carreau knows.

Another possibility is that that mypy has gotten stricter, in which case I could update the annotation rather than the logic.

**Comment by seberg** [comment]
I would guess the typing is due to NumPy 1.20 now including typing.  The `.descr` change I am confused about though, since I am not aware of a change.

**Comment by joshmoore** [comment]
Asked for vetoes in gitter. Since all PRs are currently failing, I'm going to merge and start re-running the builds. If there are any issues with the changes here, I'll be happy to open a follow-up PR.
